- name: "Hosting A Simple Site"
  hosts: amazon
  become: true
  tasks:

    - name: "Installing Apache Webserver and PHP"
      yum:
        name: [httpd , php]
        state: present

    - name: "Creating httpd.conf from template"
      template:
        src: "httpd.conf.tmpl"
        dest: "/etc/httpd/conf/httpd.conf"
        owner: "root"
        group: "root"

    - name: "Creating php.ini from template"
      template:
        src: "php.ini.templ"
        dest: "/etc/php.ini.templ"
        owner: "root"
        group: "root"

     - name: "Creating VirtualHost For {{httpd_domain}}"
      template:
        src: virtualhost.conf.tmpl
        dest: "/etc/httpd/conf.d/{{httpd_domain}}.conf"
        owner: "{{ httpd_user }}"
        group: "{{ httpd_group }}"


    - name: "Restarting/Enabling httpd Service"
      service:
        name: httpd
        state: restarted
        enabled: true
