- name: "Hosting A Simple Site"
  hosts: amazon
  become: true
  tasks:

    - name: "Installing Apache Webserver"
      yum:
        name: httpd
        state: present

    - name: "Creating httpd.conf from template"
      template:
        src: "httpd.conf.tmpl"
        dest: "/etc/httpd/conf/httpd.conf"
        owner: "root"
        group: "root"

     - name: "Creating VirtualHost For {{httpd_domain}}"
      template:
        src: virtualhost.conf.tmpl
        dest: "/etc/httpd/conf.d/{{httpd_domain}}.conf"
        owner: "{{ httpd_user }}"
        group: "{{ httpd_group }}"

    - name: "Creating Documentroot For {{httpd_domain}}"
      file:
        path: "/var/www/html/{{ httpd_domain }}"
        state: directory
        owner: "{{ httpd_user }}"
        group: "{{ httpd_group }}"

    - name: "Restarting/Enabling httpd Service"
      service:
        name: httpd
        state: restarted
        enabled: true
