- name: "Hosting A Simple Site"
  hosts: amazon
  become: true
  tasks:

    - name: "Installing Apache Webserver"
      yum:
        name: httpd
        state: present

    - name: "Restarting/Enabling httpd Service"
      service:
        name: httpd
        state: restarted
        enabled: true
